### PR TITLE
Update upstream and fix tests

### PR DESCRIPTION
**Pull request by jbearer**
After the last sync, some tests were broken which have since been fixed upstream, and we were also already hundreds of commits behind, so trying another sync.

### CODE REVIEW

**Review by sveitser — APPROVED** [review]
Looked through our own commits and LGTM. I think if the CI passes we should merge.

**Comment by sveitser** [comment]
@jbearer Does the nix shell work for you? I'm getting

```
nix develop                                                                                                        0.002s  fix/tests  17:05:24
error: builder for '/nix/store/v37pnrzzm5czbig6jckvc8mq0i28gjw0-source.drv' failed with exit code 1;
       last 7 log lines:
       >
       > trying https://github.com/foundry-rs/foundry/releases/download/nightly-94ae8974c1ac479f8d6c8ba5832b852afccfd0c5/foundry_nightly_linux_amd64.tar.gz
       >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
       >                                  Dload  Upload   Total   Spent    Left  Speed
       >   0     9    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
       > curl: (22) The requested URL returned error: 404
       > error: cannot download source from any mirror
       For full logs, run 'nix log /nix/store/v37pnrzzm5czbig6jckvc8mq0i28gjw0-source.drv'.
error: 1 dependencies of derivation '/nix/store/fb0g7prlivvynzg4fni75f249dmi6zgn-foundry-0.0.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/759aqpkid1hmvpqhzjl51qavyac7fljq-nix-shell-env.drv' failed to build
```

**Comment by jbearer** [comment]
Hmm it works for me but I do get a 404 from that foundry release. I wonder if they yanked the release and my Nix shell is building from cache?

**Comment by sveitser** [comment]
Maybe we can go back to using `  inputs.foundry.url = "github:shazow/foundry.nix/monthly";`. I think I added a particular commit when I was debugging the mismatching bindings but since we have to use docker for that anyway we might as well use the monthly branch of `foundry.nix` if it works.

**Comment by jbearer** [comment]
I'll try that

**Comment by sveitser** [comment]
What commands do you use to test locally?

**Comment by jbearer** [comment]
For this one, in `packages/contracts-bedrock` `pnpm gas-snapshot` should succeed and not result in any changes. It seems to have worked. Can you pull and check if the Nix shell builds now?

**Comment by sveitser** [comment]
> For this one, in `packages/contracts-bedrock` `pnpm gas-snapshot` should succeed and not result in any changes. It seems to have worked. Can you pull and check if the Nix shell builds now?

Works and diff is empty.

**Pull request merged**
